### ISSUE TITLE
No module named opencmiss.iron even when python bindings installed/virtualenv activated

### ISSUE THREAD

**Issue by PrasadBabarendaGamage** [OpenCMISS/manage#88]
```
cd /home/psam012/opt/OpenCMISS/develop/build/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/iron/debug
make install
...
...
[ 96%] Built target iron_python
Generating bindingsinfo_iron_py27_$<LOWER_CASE:$<CONFIG>>.py.
Generating script_virtualenv_create_and_install.cmake.
[ 97%] Built target collect_python_binding_files
[ 99%] Built target ComplexMesh
[100%] Built target Laplace_C
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/libirond.so
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/cmake/iron-config.cmake
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/cmake/iron-config-debug.cmake
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/cmake/iron-config-version.cmake
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/cmake/iron-config-dependencies.cmake
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/include/opencmiss
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/include/opencmiss/opencmiss.mod
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/include/opencmiss/opencmiss_iron_c.mod
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/include/opencmiss/opencmiss_iron.mod
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/libiron_cd.so
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/include/opencmiss/iron.h
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/include/opencmiss/iron_c_export.h
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug/opencmiss.iron/setup.py
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug/opencmiss.iron/opencmiss/__init__.py
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug/opencmiss.iron/opencmiss/iron/__init__.py
-- Installing: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug/opencmiss.iron/opencmiss/iron/iron.py
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug/opencmiss.iron/opencmiss/iron/_utils.py
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug/opencmiss.iron/opencmiss/iron/_iron_python.so
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/share/python/bindingsinfo_iron_py27_debug.py
-- Up-to-date: /home/psam012/opt/OpenCMISS/develop/install/share/python/opencmisslibraries.py

 source ~/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/virtual_environments/oclibs_venv_py27_debug/bin/activate

(oclibs_venv_py27_debug) psam012@bn369532:~/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import opencmiss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named opencmiss
>>> from opencmiss.iron import iron
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named opencmiss.iron
>>> 
```

**Comment by PrasadBabarendaGamage** [comment]
Previously I did something like:
```
cd /home/psam012/hpc/opt/OpenCMISS/cercmissprd01/main/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/python/Release
python setup.py install --force
```
but there is no longer a 'python/' folder under mpich_release

**Comment by hsorby** [comment]
This directory has been moved in your case the directory would now be:

```
cd /home/psam012/hpc/opt/OpenCMISS/cercmissprd01/main/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/pythonX.Y/Release
```

Where X and Y are the major and minor versions of Python the binaries a built for.

**Comment by hsorby** [comment]
But you are better off using the command:

```
pip install /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug/opencmiss.iron/
```
in the case given above.  This is because the pip command is used to initially install Iron and Zinc into the virtual environment and there is a slight difference between what the two commands do.  I think this would save you from having to use the force option.

**Comment by hsorby** [comment]
What is in the directory:

```
~/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/virtual_environments/oclibs_venv_py27_debug/lib/python2.7/site-packages/
```

?

**Comment by PrasadBabarendaGamage** [comment]
Thanks Hugh,

`(oclibs_venv_py27_debug) psam012@bn369532:~/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug$ pip install /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/lib/python2.7/debug/opencmiss.iron/`

produces:

`bash: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/virtual_environments/oclibs_venv_py27_debug/bin/pip: /home/psam012/opt/OpenCMISS/develop/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mp: bad interpreter: No such file or directory`

The python bindings were previously installed when OpenCMISS was built. We just needed to do a 
`source /home/psam012/hpc/opt/OpenCMISS/cercmissprd01/main/install/x86_64_linux/gnu-C5.4-gnu-F5.4/mpich_release/virtual_environments/oclibs_venv_py27_release/bin/activate`
to activate the environment.

Just wondering if I need to manually redo the pip install command each time I make any changes to the source /rebuild? I think I was using the command in the previous paragraph so that I could run programs immediately after building without any manual steps in-between.  Occasionally, it would not work so I would need to do a manual force install.

**Comment by hsorby** [comment]
If you are building from the Iron build directory you will need to issue the command: `make install` to properly install the libraries, this command will update the virtual environment with the newly created binaries.  If you just use the `make` command you will only update the binaries in the build tree and these changes will not be available through the virtual environment.

**Comment by PrasadBabarendaGamage** [comment]
Hi Hugh, I have been using make install, but the binding are not available through the virtual environment. I'll come and bug you this afternoon : )

**Comment by hsorby** [comment]
Closing as this is now fixed.
